"use client"

import React, { useCallback, useEffect, useState } from "react"
import axios from "axios"
import toast from "react-hot-toast"
import QRCode from "qrcode"
import Image from "next/image"
import { loadWallets, StoredWallet } from "@/lib/walletStorage"

interface CryptoPaymentProps {
  plan: 'STARTER' | 'PRO' | 'ENTERPRISE'
  amount: number
  onSuccess?: () => void
  onCancel?: () => void
}

export default function CryptoPayment({ plan, amount, onSuccess, onCancel }: CryptoPaymentProps) {
  const [loading, setLoading] = useState(false)
  const [payment, setPayment] = useState<any>(null)
  const [manualWallet, setManualWallet] = useState<{ currency: string; network: string; address: string; label?: string } | null>(null)
  const [network, setNetwork] = useState<'TRC20' | 'ERC20' | 'BEP20'>('TRC20')
  const [txHash, setTxHash] = useState("")
  const [qrCode, setQrCode] = useState("")
  const [autoGenerated, setAutoGenerated] = useState(false)

  const applyManualWallet = useCallback(async (wallet: StoredWallet, showToast = true) => {
    setManualWallet({ currency: wallet.currency, network: wallet.network, address: wallet.address, label: wallet.label })
    try {
      const qr = await QRCode.toDataURL(wallet.address, {
        width: 300,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#ffffff'
        }
      })
      setQrCode(qr)
    } catch (err) {
      console.error("Failed to generate QR for manual wallet", err)
    }
    if (showToast) {
      toast.success("Using your enterprise wallet configuration for this payment.")
    }
  }, [])

  const createPayment = async (targetNetwork: 'TRC20' | 'ERC20' | 'BEP20' = network) => {
    try {
      setLoading(true)
      const { data } = await axios.post('/api/crypto-payment/create', {
        plan,
        network: targetNetwork
      })
      
      setPayment(data.payment)
      setManualWallet(null)
      setNetwork(targetNetwork)
      
      // Generate QR code with wallet address
      if (data.payment.walletAddress) {
        const qr = await QRCode.toDataURL(data.payment.walletAddress, {
          width: 300,
          margin: 2,
          color: {
            dark: '#000000',
            light: '#ffffff'
          }
        })
        setQrCode(qr)
      }
      
      toast.success("✅ Payment address generated! Send USDT to complete.")
    } catch (error: any) {
      console.error('Payment creation error:', error)
      const storedWallets = loadWallets()
      if (storedWallets.length) {
        const matching = storedWallets.find(
          (wallet) => wallet.network.toUpperCase() === network && wallet.currency === 'USDT'
        ) || storedWallets.find((wallet) => wallet.network.toUpperCase() === network) || storedWallets.find((wallet) => wallet.isPrimary) || storedWallets[0]

        if (matching) {
          await applyManualWallet(matching)
          setPayment((prev: any) => prev ?? {
            id: `manual-${matching.id}`,
            walletAddress: matching.address,
            reference: matching.label || matching.id,
            network: matching.network,
            currency: matching.currency,
          })
          return
        }
      }

      toast.error(error.response?.data?.error || "Failed to create payment")
    } finally {
      setLoading(false)
    }
  }

  // Auto-generate payment on component mount
  useEffect(() => {
    if (!payment && !autoGenerated && !loading) {
      setAutoGenerated(true)
      createPayment()
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!manualWallet) return
    const storedWallets = loadWallets()
    if (!storedWallets.length) return
    const desired = storedWallets.find(
      (wallet) => wallet.network.toUpperCase() === network && wallet.currency === manualWallet.currency
    ) || storedWallets.find((wallet) => wallet.network.toUpperCase() === network)

    if (desired && desired.address !== manualWallet.address) {
      applyManualWallet(desired, false)
      setPayment((prev: any) => prev ?? {
        id: `manual-${desired.id}`,
        walletAddress: desired.address,
        reference: desired.label || desired.id,
        network: desired.network,
        currency: desired.currency,
      })
    }
  }, [network, manualWallet, applyManualWallet])

  const submitPayment = async () => {
    if (!txHash) {
      toast.error("Please enter transaction hash")
      return
    }

    if (manualWallet && payment?.id?.startsWith('manual-')) {
      setLoading(true)
      try {
        await new Promise(resolve => setTimeout(resolve, 600))
        toast.success("Transaction received! We'll verify and activate shortly.")
        setTxHash("")
        onSuccess?.()
      } finally {
        setLoading(false)
      }
      return
    }

    try {
      setLoading(true)
      await axios.post('/api/crypto-payment/confirm', {
        paymentId: payment.id,
        txHash
      })
      
      toast.success("Payment submitted! We'll verify it shortly (usually within 1 hour)")
      onSuccess?.()
    } catch (error: any) {
      toast.error(error.response?.data?.error || "Failed to submit payment")
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    toast.success("Copied to clipboard!")
  }

  const handleNetworkSelect = (value: 'TRC20' | 'ERC20' | 'BEP20') => {
    if (value === network) {
      return
    }

    setNetwork(value)

    if (!manualWallet && autoGenerated) {
      setPayment(null)
      setQrCode("")
      setAutoGenerated(true)
      createPayment(value)
    }
  }

  const activeAddress = manualWallet?.address || payment?.walletAddress
  const activeNetwork = (manualWallet?.network || payment?.network || network).toUpperCase()
  const activeCurrency = manualWallet?.currency || payment?.currency || 'USDT'
  const paymentReference = payment?.reference || manualWallet?.label || payment?.id || 'ADMIN-CONFIG'

  if (!payment && !manualWallet) {
    return (
      <div className="space-y-6">
        <div className="text-center">
          <h3 className="text-2xl font-bold mb-2">Pay with USDT</h3>
          <p className="text-white/60">Fast, secure cryptocurrency payment</p>
        </div>

        <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
          <h4 className="font-semibold mb-2">💎 Why Choose Crypto?</h4>
          <ul className="text-sm text-white/80 space-y-1">
            <li>✅ Instant activation (after verification)</li>
            <li>✅ Lower fees than credit cards</li>
            <li>✅ Anonymous payments</li>
            <li>✅ Global accessibility</li>
          </ul>
        </div>

        <div>
          <label className="block text-sm font-medium mb-2">Select Network</label>
          <select
            value={network}
            onChange={(e) => handleNetworkSelect(e.target.value as 'TRC20' | 'ERC20' | 'BEP20')}
            className="w-full px-4 py-3 bg-black/30 border border-white/10 rounded-lg focus:border-blue-500 focus:outline-none"
          >
            <option value="TRC20">USDT TRC20 (Tron) - Recommended</option>
            <option value="ERC20">USDT ERC20 (Ethereum)</option>
            <option value="BEP20">USDT BEP20 (BNB Chain)</option>
          </select>
          <p className="text-xs text-white/40 mt-2">
            TRC20 recommended for lowest fees (~$1)
          </p>
        </div>

        <div className="bg-gradient-to-r from-blue-500/20 to-purple-500/20 border border-blue-500/30 rounded-lg p-6 text-center">
          <div className="text-sm text-white/60 mb-2">Total Amount</div>
          <div className="text-4xl font-bold mb-1">${amount} USDT</div>
          <div className="text-sm text-white/60">
            {plan.charAt(0) + plan.slice(1).toLowerCase()} Plan
          </div>
        </div>

        <button
          onClick={() => createPayment(network)}
          disabled={loading}
          className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-blue-600/50 text-white font-semibold py-4 px-6 rounded-lg transition-colors"
        >
          {loading ? "Creating Payment..." : "Generate Payment Address"}
        </button>

        {onCancel && (
          <button
            onClick={onCancel}
            className="w-full bg-white/5 hover:bg-white/10 text-white font-semibold py-3 px-6 rounded-lg transition-colors"
          >
            Cancel
          </button>
        )}
      </div>
    )
  }

  return (
    <div className="space-y-6">
        <div className="text-center">
          <h3 className="text-2xl font-bold mb-2">Send USDT Payment</h3>
          <p className="text-white/60">Scan QR or copy address below</p>
        </div>

        <div className="bg-gradient-to-r from-green-500/10 to-blue-500/10 border border-green-500/20 rounded-lg p-6">
        <div className="grid md:grid-cols-2 gap-4 mb-4">
          <div>
            <label className="block text-sm font-medium mb-2">Payment Network</label>
            <select
              value={network}
              onChange={(e) => handleNetworkSelect(e.target.value as 'TRC20' | 'ERC20' | 'BEP20')}
              className="w-full px-4 py-3 bg-black/30 border border-white/10 rounded-lg focus:border-blue-500 focus:outline-none"
            >
              <option value="TRC20">USDT TRC20 (Tron) - Recommended</option>
              <option value="ERC20">USDT ERC20 (Ethereum)</option>
              <option value="BEP20">USDT BEP20 (BNB Chain)</option>
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium mb-2">Wallet Source</label>
            <div className={`w-full px-4 py-3 rounded-lg border ${(manualWallet ? "border-yellow-500/40 bg-yellow-500/10 text-yellow-100" : "border-blue-500/40 bg-blue-500/10 text-blue-100")}`}>
              {manualWallet ? "Admin-configured wallet" : "Auto-generated secure wallet"}
            </div>
          </div>
        </div>
        <div className="text-center mb-4">
          <div className="text-sm text-white/60 mb-1">Amount to Send</div>
          <div className="text-3xl font-bold text-green-400">${amount} {activeCurrency}</div>
          <div className="text-xs text-white/60 mt-1">{activeNetwork} Network</div>
        </div>

        {manualWallet && (
          <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-3 text-sm text-yellow-200 mb-4">
            Using admin-configured wallet: <span className="font-mono text-yellow-100">{manualWallet.address}</span>
          </div>
        )}

        {qrCode && activeAddress && !manualWallet && (
          <div className="bg-white p-4 rounded-lg mb-4 mx-auto w-fit">
            <Image src={qrCode} alt="Payment QR Code" width={192} height={192} unoptimized className="w-48 h-48" />
          </div>
        )}

        <div>
          <label className="block text-sm font-medium mb-2">Wallet Address</label>
          <div className="flex gap-2">
            <input
              type="text"
              value={activeAddress || ""}
              readOnly
              className="flex-1 px-4 py-3 bg-black/30 border border-white/10 rounded-lg font-mono text-sm"
            />
            <button
              onClick={() => activeAddress && copyToClipboard(activeAddress)}
              className="px-4 py-3 bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
              disabled={!activeAddress}
            >
              📋 Copy
            </button>
          </div>
        </div>

        <div className="mt-4 p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-lg">
          <p className="text-sm text-yellow-200/80">
            <span className="font-bold">⚠️ Important:</span> Only send USDT on {network} network.
            Sending other tokens or using wrong network will result in loss of funds!
          </p>
        </div>
      </div>

      <div>
        <label className="block text-sm font-medium mb-2">
          Transaction Hash (after sending)
        </label>
        <input
          type="text"
          value={txHash}
          onChange={(e) => setTxHash(e.target.value)}
          placeholder="Enter transaction hash from your wallet"
          className="w-full px-4 py-3 bg-black/30 border border-white/10 rounded-lg focus:border-blue-500 focus:outline-none font-mono text-sm"
        />
        <p className="text-xs text-white/40 mt-2">
          Find this in your wallet after sending the payment
        </p>
      </div>

      <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4">
        <h4 className="font-semibold mb-2">📝 Payment Instructions:</h4>
        <ol className="text-sm text-white/80 space-y-2 list-decimal list-inside">
          <li>Open your crypto wallet (Trust Wallet, MetaMask, etc.)</li>
          <li>Send exactly <span className="font-bold text-green-400">${amount} USDT</span> to the address above</li>
          <li>Make sure you select <span className="font-bold">{network}</span> network</li>
          <li>Copy the transaction hash from your wallet</li>
          <li>Paste it in the field above and click Submit</li>
          <li>We'll verify and activate your plan within 1 hour!</li>
        </ol>
      </div>

      <button
        onClick={submitPayment}
        disabled={loading || !txHash}
        className="w-full bg-green-600 hover:bg-green-700 disabled:bg-green-600/50 text-white font-semibold py-4 px-6 rounded-lg transition-colors"
      >
        {loading ? "Submitting..." : "✅ I've Sent Payment - Verify Now"}
      </button>

      <div className="text-center">
        <p className="text-sm text-white/60">
          Payment expires in 1 hour • Reference: <span className="font-mono">{paymentReference}</span>
        </p>
      </div>
    </div>
  )
}
